version: '3.8'

services:
  # Servicio para la base de datos MySQL
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password       # Contrase침a del root para MySQL
      MYSQL_DATABASE: inventory_db            # Nombre de la base de datos
      MYSQL_USER: user                        # Usuario de base de datos
      MYSQL_PASSWORD: user_password           # Contrase침a del usuario
    ports:
      - "3306:3306"                           # Exponemos el puerto 3306
    volumes:
      - ./data:/var/lib/mysql                 # Volumen para persistir los datos
    networks:
      - app-network

  # Servicio para el microservicio de productos (MsProductos)
  msproductos:
    build:
      context: ./MsProductos                  # Ruta donde est치 el c칩digo del microservicio de productos
      dockerfile: Dockerfile                   # Usamos el Dockerfile que hemos definido
    container_name: msproductos
    ports:
      - "8081:8080"                           # Exponemos el puerto 8080 del microservicio
    depends_on:
      - db                                     # El microservicio depende de la base de datos
    networks:
      - app-network

  # Red de contenedores
networks:
  app-network:
    driver: bridge
