server:
  port: 6001

jwt:
  secret: Key#SuperSecret$PolyglotTest#JavaMicroservices#2025unu

spring:
  application:
    name:  Gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:      
      - id: MsProveedores
        uri: http://localhost:8084
        predicates:
          - Path=/proveedor/**
        filters:
          - StripPrefix=1
      - id: appinvoice
        uri: http://localhost:82
        predicates:
          - Path=/invoice/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: apppay
        uri: http://localhost:83
        predicates:
          - Path=/pay/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: apptransaction
        uri: http://localhost:84
        predicates:
          - Path=/transaction/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
           