server:
  port: 6001

jwt:
  secret: Key#SuperSecret$PolyglotTest#JavaMicroservices#924051891

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:      
      - id: MsProveedores
        uri: http://localhost:84
        predicates:
          - Path=/proveedor/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter

      - id: apptransaction
        uri: http://localhost:84
        predicates:
          - Path=/transaction/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
           
  
