server:
  port: 6003

jwt:
  secret: Key#SuperSecret$PolyglotTest#JavaMicroservices#924051891

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:      
      - id: MsProveedores
        uri: http://localhost:8084
        predicates:
          - Path=/proveedor/**
        filters:
          - StripPrefix=1
      - id: appMsCliente
        uri: http://localhost:8085
        predicates:
          - Path=/MsCliente/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
           
  
